kind: pipeline
name: build

steps:
- name: backend
  image: golang:1.11
  commands:
  - go build
  - go test -v

- name: frontend
  image: node
  commands:
    - npm install
    - npm run test
    - npm run lint

services:
- name: redis
  image: redis:latest
  ports:
  - 6379
  volumes:
  - name: foo
    path: /bar

volumes:
- name: foo
  temp: {}

---
kind: pipeline
name: notify

steps:
- name: notify
  image: plugins/slack
  settings:
    room: general
    token:
      from_secret: token

node:
  disk: ssd

depends_on:
- build
